# Generated by Django 4.1.1 on 2022-10-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentCrm',
        ),
    ]
